blank_issues_enabled: false
contact_links:
  - name: Innovation Challenge Website
    url: https://innovation.minima.global/
    about: Find out more about the Minima Innovation Challenge here
  - name: Minima Community Support
    url: https://discord.gg/ztnSCaAMye
    about: For support, please reach out to a member of the Team in Discord.
